---

- name: pull an image
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Set selenium server on
      become: true
      docker_container:
        name: sel_server
        detach: true
        ports: "4444:4444"
        image: selenium/standalone-firefox:3.10.0-argon
        state: started

    - name: Set up of the mariobd7/prueba_1:latest image
      become: true
      docker_container:
        name: ansible_container
        tty: true
        network_mode: host
        volumes: /tmp/.X11-unix
        expose: DISPLAY
        image: mariobd7/prueba_5:first
